/*
 * generated by Xtext
 */
package br.ufrn.dimap.ase.dsl.ui.contentassist;

import br.ufrn.dimap.ase.dsl.ui.contentassist.AbstractExpDslv2ProposalProvider;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class ExpDslv2ProposalProvider extends AbstractExpDslv2ProposalProvider {

}
