/*
 * generated by Xtext
 */
package br.ufrn.dimap.ase.dsl;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class ExpDslv2RuntimeModule extends
		br.ufrn.dimap.ase.dsl.AbstractExpDslv2RuntimeModule {

}
