/*
 * generated by Xtext
 */
package br.ufrn.dimap.ase.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ExpDslv2OutlineTreeProvider extends DefaultOutlineTreeProvider {

}
