/*
* generated by Xtext
*/
package br.ufrn.dimap.ase.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import br.ufrn.dimap.ase.dsl.services.Expdslv3GrammarAccess;

public class Expdslv3Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Expdslv3GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected br.ufrn.dimap.ase.dsl.parser.antlr.internal.InternalExpdslv3Parser createParser(XtextTokenStream stream) {
		return new br.ufrn.dimap.ase.dsl.parser.antlr.internal.InternalExpdslv3Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public Expdslv3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Expdslv3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
