/*
* generated by Xtext
*/

package org.xtext.project.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ExpDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsExperimentElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Model:
		//	elements+=ExperimentElement*;
		public ParserRule getRule() { return rule; }

		//elements+=ExperimentElement*
		public Assignment getElementsAssignment() { return cElementsAssignment; }

		//ExperimentElement
		public RuleCall getElementsExperimentElementParserRuleCall_0() { return cElementsExperimentElementParserRuleCall_0; }
	}

	public class ExperimentElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExperimentElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cProcessKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cProcessAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cProcessProcessParserRuleCall_0_1_0 = (RuleCall)cProcessAssignment_0_1.eContents().get(0);
		private final Keyword cEndKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cExperimentalPlanKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cExperimentsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cExperimentsExperimentalPlanParserRuleCall_1_1_0 = (RuleCall)cExperimentsAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cGeneralQuestionsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cQuestionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cQuestionQuestionParserRuleCall_2_1_0 = (RuleCall)cQuestionAssignment_2_1.eContents().get(0);
		
		//ExperimentElement:
		//	("Process" process+=Process* "end") ("Experimental Plan" experiments+=ExperimentalPlan*)? ("General Questions"
		//	question+=Question*)?;
		public ParserRule getRule() { return rule; }

		//("Process" process+=Process* "end") ("Experimental Plan" experiments+=ExperimentalPlan*)? ("General Questions"
		//question+=Question*)?
		public Group getGroup() { return cGroup; }

		//"Process" process+=Process* "end"
		public Group getGroup_0() { return cGroup_0; }

		//"Process"
		public Keyword getProcessKeyword_0_0() { return cProcessKeyword_0_0; }

		//process+=Process*
		public Assignment getProcessAssignment_0_1() { return cProcessAssignment_0_1; }

		//Process
		public RuleCall getProcessProcessParserRuleCall_0_1_0() { return cProcessProcessParserRuleCall_0_1_0; }

		//"end"
		public Keyword getEndKeyword_0_2() { return cEndKeyword_0_2; }

		//("Experimental Plan" experiments+=ExperimentalPlan*)?
		public Group getGroup_1() { return cGroup_1; }

		//"Experimental Plan"
		public Keyword getExperimentalPlanKeyword_1_0() { return cExperimentalPlanKeyword_1_0; }

		//experiments+=ExperimentalPlan*
		public Assignment getExperimentsAssignment_1_1() { return cExperimentsAssignment_1_1; }

		//ExperimentalPlan
		public RuleCall getExperimentsExperimentalPlanParserRuleCall_1_1_0() { return cExperimentsExperimentalPlanParserRuleCall_1_1_0; }

		//("General Questions" question+=Question*)?
		public Group getGroup_2() { return cGroup_2; }

		//"General Questions"
		public Keyword getGeneralQuestionsKeyword_2_0() { return cGeneralQuestionsKeyword_2_0; }

		//question+=Question*
		public Assignment getQuestionAssignment_2_1() { return cQuestionAssignment_2_1; }

		//Question
		public RuleCall getQuestionQuestionParserRuleCall_2_1_0() { return cQuestionQuestionParserRuleCall_2_1_0; }
	}

	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_0_0_0 = (RuleCall)cNameAssignment_0_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cActivitiesAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cActivitiesActivityParserRuleCall_0_2_0 = (RuleCall)cActivitiesAssignment_0_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cMetricsKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cMetricsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMetricsMetricsParserRuleCall_1_1_0 = (RuleCall)cMetricsAssignment_1_1.eContents().get(0);
		private final Keyword cEndKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSpecificQuestionsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cQuestionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cQuestionQuestionParserRuleCall_2_1_0 = (RuleCall)cQuestionAssignment_2_1.eContents().get(0);
		private final Keyword cEndKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		////WorkbreakdownStructure	
		//Process:
		//	(name=STRING "{" activities+=Activity* "}") ("metrics" metrics+=Metrics* "end")? ("Specific Questions"
		//	question+=Question* "end")?;
		public ParserRule getRule() { return rule; }

		//(name=STRING "{" activities+=Activity* "}") ("metrics" metrics+=Metrics* "end")? ("Specific Questions"
		//question+=Question* "end")?
		public Group getGroup() { return cGroup; }

		//name=STRING "{" activities+=Activity* "}"
		public Group getGroup_0() { return cGroup_0; }

		//name=STRING
		public Assignment getNameAssignment_0_0() { return cNameAssignment_0_0; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0_0_0() { return cNameSTRINGTerminalRuleCall_0_0_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0_1() { return cLeftCurlyBracketKeyword_0_1; }

		//activities+=Activity*
		public Assignment getActivitiesAssignment_0_2() { return cActivitiesAssignment_0_2; }

		//Activity
		public RuleCall getActivitiesActivityParserRuleCall_0_2_0() { return cActivitiesActivityParserRuleCall_0_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_0_3() { return cRightCurlyBracketKeyword_0_3; }

		//("metrics" metrics+=Metrics* "end")?
		public Group getGroup_1() { return cGroup_1; }

		//"metrics"
		public Keyword getMetricsKeyword_1_0() { return cMetricsKeyword_1_0; }

		//metrics+=Metrics*
		public Assignment getMetricsAssignment_1_1() { return cMetricsAssignment_1_1; }

		//Metrics
		public RuleCall getMetricsMetricsParserRuleCall_1_1_0() { return cMetricsMetricsParserRuleCall_1_1_0; }

		//"end"
		public Keyword getEndKeyword_1_2() { return cEndKeyword_1_2; }

		//("Specific Questions" question+=Question* "end")?
		public Group getGroup_2() { return cGroup_2; }

		//"Specific Questions"
		public Keyword getSpecificQuestionsKeyword_2_0() { return cSpecificQuestionsKeyword_2_0; }

		//question+=Question*
		public Assignment getQuestionAssignment_2_1() { return cQuestionAssignment_2_1; }

		//Question
		public RuleCall getQuestionQuestionParserRuleCall_2_1_0() { return cQuestionQuestionParserRuleCall_2_1_0; }

		//"end"
		public Keyword getEndKeyword_2_2() { return cEndKeyword_2_2; }
	}

	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActivityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cNextAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNextIDTerminalRuleCall_3_0 = (RuleCall)cNextAssignment_3.eContents().get(0);
		private final Assignment cRoleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRoleRoleParserRuleCall_4_0 = (RuleCall)cRoleAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTasksAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTasksTaskParserRuleCall_5_1_0 = (RuleCall)cTasksAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		
		//Activity:
		//	"Activity" id=ID name=STRING next+=ID? role+=Role* ("{" tasks+=Task* "}")?;
		public ParserRule getRule() { return rule; }

		//"Activity" id=ID name=STRING next+=ID? role+=Role* ("{" tasks+=Task* "}")?
		public Group getGroup() { return cGroup; }

		//"Activity"
		public Keyword getActivityKeyword_0() { return cActivityKeyword_0; }

		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }

		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }

		//next+=ID?
		public Assignment getNextAssignment_3() { return cNextAssignment_3; }

		//ID
		public RuleCall getNextIDTerminalRuleCall_3_0() { return cNextIDTerminalRuleCall_3_0; }

		//role+=Role*
		public Assignment getRoleAssignment_4() { return cRoleAssignment_4; }

		//Role
		public RuleCall getRoleRoleParserRuleCall_4_0() { return cRoleRoleParserRuleCall_4_0; }

		//("{" tasks+=Task* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_0() { return cLeftCurlyBracketKeyword_5_0; }

		//tasks+=Task*
		public Assignment getTasksAssignment_5_1() { return cTasksAssignment_5_1; }

		//Task
		public RuleCall getTasksTaskParserRuleCall_5_1_0() { return cTasksTaskParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_2() { return cRightCurlyBracketKeyword_5_2; }
	}

	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Task");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTaskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Task:
		//	"Task" name=STRING;
		public ParserRule getRule() { return rule; }

		//"Task" name=STRING
		public Group getGroup() { return cGroup; }

		//"Task"
		public Keyword getTaskKeyword_0() { return cTaskKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}

	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Role:
		//	"Role" name=STRING;
		public ParserRule getRule() { return rule; }

		//"Role" name=STRING
		public Group getGroup() { return cGroup; }

		//"Role"
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}

	public class ExperimentalPlanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExperimentalPlan");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDesignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeDesignTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFactorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFactorFactorParserRuleCall_5_0 = (RuleCall)cFactorAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		////CRD – Completely Randomized Design
		////RCBD – Randomized Complete Block Design
		////LS – Latin Square
		//ExperimentalPlan:
		//	"Design" name=STRING "type" type=DesignType "{" factor+=Factor* "}";
		public ParserRule getRule() { return rule; }

		//"Design" name=STRING "type" type=DesignType "{" factor+=Factor* "}"
		public Group getGroup() { return cGroup; }

		//"Design"
		public Keyword getDesignKeyword_0() { return cDesignKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"type"
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }

		//type=DesignType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//DesignType
		public RuleCall getTypeDesignTypeEnumRuleCall_3_0() { return cTypeDesignTypeEnumRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//factor+=Factor*
		public Assignment getFactorAssignment_5() { return cFactorAssignment_5; }

		//Factor
		public RuleCall getFactorFactorParserRuleCall_5_0() { return cFactorFactorParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class FactorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Factor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFactorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLevelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLevelLevelsParserRuleCall_3_0 = (RuleCall)cLevelAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Factor:
		//	"Factor" name=STRING "{" level+=Levels* "}";
		public ParserRule getRule() { return rule; }

		//"Factor" name=STRING "{" level+=Levels* "}"
		public Group getGroup() { return cGroup; }

		//"Factor"
		public Keyword getFactorKeyword_0() { return cFactorKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//level+=Levels*
		public Assignment getLevelAssignment_3() { return cLevelAssignment_3; }

		//Levels
		public RuleCall getLevelLevelsParserRuleCall_3_0() { return cLevelLevelsParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class LevelsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Levels");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLevelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Levels:
		//	"Level" name=STRING;
		public ParserRule getRule() { return rule; }

		//"Level" name=STRING
		public Group getGroup() { return cGroup; }

		//"Level"
		public Keyword getLevelKeyword_0() { return cLevelKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}

	public class MetricsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Metrics");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cActivityMetricParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTaskMetricParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Metrics:
		//	ActivityMetric | TaskMetric;
		public ParserRule getRule() { return rule; }

		//ActivityMetric | TaskMetric
		public Alternatives getAlternatives() { return cAlternatives; }

		//ActivityMetric
		public RuleCall getActivityMetricParserRuleCall_0() { return cActivityMetricParserRuleCall_0; }

		//TaskMetric
		public RuleCall getTaskMetricParserRuleCall_1() { return cTaskMetricParserRuleCall_1; }
	}

	public class ActivityMetricElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ActivityMetric");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMetricKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cRelatesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cProcessNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProcessNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cProcessNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTypeMetricTypeEnumRuleCall_6_1_0 = (RuleCall)cTypeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFormKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cFormAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cFormColectTypeEnumRuleCall_7_1_0 = (RuleCall)cFormAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cIdKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cIdAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cIdSTRINGTerminalRuleCall_8_1_0 = (RuleCall)cIdAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cUnitKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cUnitAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cUnitMetricUnitEnumRuleCall_9_1_0 = (RuleCall)cUnitAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cActivityBeginKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cActivityBeginAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cActivityBeginSTRINGTerminalRuleCall_10_1_0 = (RuleCall)cActivityBeginAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cActivityEndKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cActivityEndAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cActivityEndSTRINGTerminalRuleCall_11_1_0 = (RuleCall)cActivityEndAssignment_11_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//ActivityMetric:
		//	"Metric" name=STRING "relates" processName+=STRING* "{" ("description" description=STRING) ("type" type=MetricType)
		//	("form" form=ColectType)? ("id" id=STRING) ("unit" unit=MetricUnit)? ("activityBegin" activityBegin=STRING)
		//	("activityEnd" activityEnd=STRING) "}";
		public ParserRule getRule() { return rule; }

		//"Metric" name=STRING "relates" processName+=STRING* "{" ("description" description=STRING) ("type" type=MetricType)
		//("form" form=ColectType)? ("id" id=STRING) ("unit" unit=MetricUnit)? ("activityBegin" activityBegin=STRING)
		//("activityEnd" activityEnd=STRING) "}"
		public Group getGroup() { return cGroup; }

		//"Metric"
		public Keyword getMetricKeyword_0() { return cMetricKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"relates"
		public Keyword getRelatesKeyword_2() { return cRelatesKeyword_2; }

		//processName+=STRING*
		public Assignment getProcessNameAssignment_3() { return cProcessNameAssignment_3; }

		//STRING
		public RuleCall getProcessNameSTRINGTerminalRuleCall_3_0() { return cProcessNameSTRINGTerminalRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//"description" description=STRING
		public Group getGroup_5() { return cGroup_5; }

		//"description"
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_1_0() { return cDescriptionSTRINGTerminalRuleCall_5_1_0; }

		//"type" type=MetricType
		public Group getGroup_6() { return cGroup_6; }

		//"type"
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }

		//type=MetricType
		public Assignment getTypeAssignment_6_1() { return cTypeAssignment_6_1; }

		//MetricType
		public RuleCall getTypeMetricTypeEnumRuleCall_6_1_0() { return cTypeMetricTypeEnumRuleCall_6_1_0; }

		//("form" form=ColectType)?
		public Group getGroup_7() { return cGroup_7; }

		//"form"
		public Keyword getFormKeyword_7_0() { return cFormKeyword_7_0; }

		//form=ColectType
		public Assignment getFormAssignment_7_1() { return cFormAssignment_7_1; }

		//ColectType
		public RuleCall getFormColectTypeEnumRuleCall_7_1_0() { return cFormColectTypeEnumRuleCall_7_1_0; }

		//"id" id=STRING
		public Group getGroup_8() { return cGroup_8; }

		//"id"
		public Keyword getIdKeyword_8_0() { return cIdKeyword_8_0; }

		//id=STRING
		public Assignment getIdAssignment_8_1() { return cIdAssignment_8_1; }

		//STRING
		public RuleCall getIdSTRINGTerminalRuleCall_8_1_0() { return cIdSTRINGTerminalRuleCall_8_1_0; }

		//("unit" unit=MetricUnit)?
		public Group getGroup_9() { return cGroup_9; }

		//"unit"
		public Keyword getUnitKeyword_9_0() { return cUnitKeyword_9_0; }

		//unit=MetricUnit
		public Assignment getUnitAssignment_9_1() { return cUnitAssignment_9_1; }

		//MetricUnit
		public RuleCall getUnitMetricUnitEnumRuleCall_9_1_0() { return cUnitMetricUnitEnumRuleCall_9_1_0; }

		//"activityBegin" activityBegin=STRING
		public Group getGroup_10() { return cGroup_10; }

		//"activityBegin"
		public Keyword getActivityBeginKeyword_10_0() { return cActivityBeginKeyword_10_0; }

		//activityBegin=STRING
		public Assignment getActivityBeginAssignment_10_1() { return cActivityBeginAssignment_10_1; }

		//STRING
		public RuleCall getActivityBeginSTRINGTerminalRuleCall_10_1_0() { return cActivityBeginSTRINGTerminalRuleCall_10_1_0; }

		//"activityEnd" activityEnd=STRING
		public Group getGroup_11() { return cGroup_11; }

		//"activityEnd"
		public Keyword getActivityEndKeyword_11_0() { return cActivityEndKeyword_11_0; }

		//activityEnd=STRING
		public Assignment getActivityEndAssignment_11_1() { return cActivityEndAssignment_11_1; }

		//STRING
		public RuleCall getActivityEndSTRINGTerminalRuleCall_11_1_0() { return cActivityEndSTRINGTerminalRuleCall_11_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class TaskMetricElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TaskMetric");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMetricKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cRelatesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cProcessNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProcessNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cProcessNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTypeMetricTypeEnumRuleCall_6_1_0 = (RuleCall)cTypeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFormKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cFormAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cFormColectTypeEnumRuleCall_7_1_0 = (RuleCall)cFormAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cIdKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cIdAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cIdSTRINGTerminalRuleCall_8_1_0 = (RuleCall)cIdAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cUnitKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cUnitAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cUnitMetricUnitEnumRuleCall_9_1_0 = (RuleCall)cUnitAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cActivitiesKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cActivitiesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cActivitiesSTRINGTerminalRuleCall_10_1_0 = (RuleCall)cActivitiesAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//TaskMetric:
		//	"Metric" name=STRING "relates" processName+=STRING* "{" ("description" description=STRING) ("type" type=MetricType)
		//	("form" form=ColectType)? ("id" id=STRING) ("unit" unit=MetricUnit)? ("activities" activities=STRING) "}";
		public ParserRule getRule() { return rule; }

		//"Metric" name=STRING "relates" processName+=STRING* "{" ("description" description=STRING) ("type" type=MetricType)
		//("form" form=ColectType)? ("id" id=STRING) ("unit" unit=MetricUnit)? ("activities" activities=STRING) "}"
		public Group getGroup() { return cGroup; }

		//"Metric"
		public Keyword getMetricKeyword_0() { return cMetricKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"relates"
		public Keyword getRelatesKeyword_2() { return cRelatesKeyword_2; }

		//processName+=STRING*
		public Assignment getProcessNameAssignment_3() { return cProcessNameAssignment_3; }

		//STRING
		public RuleCall getProcessNameSTRINGTerminalRuleCall_3_0() { return cProcessNameSTRINGTerminalRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//"description" description=STRING
		public Group getGroup_5() { return cGroup_5; }

		//"description"
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_1_0() { return cDescriptionSTRINGTerminalRuleCall_5_1_0; }

		//"type" type=MetricType
		public Group getGroup_6() { return cGroup_6; }

		//"type"
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }

		//type=MetricType
		public Assignment getTypeAssignment_6_1() { return cTypeAssignment_6_1; }

		//MetricType
		public RuleCall getTypeMetricTypeEnumRuleCall_6_1_0() { return cTypeMetricTypeEnumRuleCall_6_1_0; }

		//("form" form=ColectType)?
		public Group getGroup_7() { return cGroup_7; }

		//"form"
		public Keyword getFormKeyword_7_0() { return cFormKeyword_7_0; }

		//form=ColectType
		public Assignment getFormAssignment_7_1() { return cFormAssignment_7_1; }

		//ColectType
		public RuleCall getFormColectTypeEnumRuleCall_7_1_0() { return cFormColectTypeEnumRuleCall_7_1_0; }

		//"id" id=STRING
		public Group getGroup_8() { return cGroup_8; }

		//"id"
		public Keyword getIdKeyword_8_0() { return cIdKeyword_8_0; }

		//id=STRING
		public Assignment getIdAssignment_8_1() { return cIdAssignment_8_1; }

		//STRING
		public RuleCall getIdSTRINGTerminalRuleCall_8_1_0() { return cIdSTRINGTerminalRuleCall_8_1_0; }

		//("unit" unit=MetricUnit)?
		public Group getGroup_9() { return cGroup_9; }

		//"unit"
		public Keyword getUnitKeyword_9_0() { return cUnitKeyword_9_0; }

		//unit=MetricUnit
		public Assignment getUnitAssignment_9_1() { return cUnitAssignment_9_1; }

		//MetricUnit
		public RuleCall getUnitMetricUnitEnumRuleCall_9_1_0() { return cUnitMetricUnitEnumRuleCall_9_1_0; }

		//"activities" activities=STRING
		public Group getGroup_10() { return cGroup_10; }

		//"activities"
		public Keyword getActivitiesKeyword_10_0() { return cActivitiesKeyword_10_0; }

		//activities=STRING
		public Assignment getActivitiesAssignment_10_1() { return cActivitiesAssignment_10_1; }

		//STRING
		public RuleCall getActivitiesSTRINGTerminalRuleCall_10_1_0() { return cActivitiesSTRINGTerminalRuleCall_10_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class QuestionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Questions");
		private final Assignment cQuestionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cQuestionQuestionParserRuleCall_0 = (RuleCall)cQuestionAssignment.eContents().get(0);
		
		//Questions:
		//	question+=Question*;
		public ParserRule getRule() { return rule; }

		//question+=Question*
		public Assignment getQuestionAssignment() { return cQuestionAssignment; }

		//Question
		public RuleCall getQuestionQuestionParserRuleCall_0() { return cQuestionQuestionParserRuleCall_0; }
	}

	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Question");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeAnswerTypeEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIdAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_5_1_0 = (RuleCall)cIdAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRequiredKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cReqAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cReqINTTerminalRuleCall_6_1_0 = (RuleCall)cReqAssignment_6_1.eContents().get(0);
		private final Assignment cAlternativesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAlternativesAlternativesParserRuleCall_7_0 = (RuleCall)cAlternativesAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Question:
		//	"Question" name=STRING "{" ("description" description=STRING) ("type" type=AnswerType) ("id" id=ID) ("required"
		//	req=INT)? alternatives+=Alternatives* "}";
		public ParserRule getRule() { return rule; }

		//"Question" name=STRING "{" ("description" description=STRING) ("type" type=AnswerType) ("id" id=ID) ("required"
		//req=INT)? alternatives+=Alternatives* "}"
		public Group getGroup() { return cGroup; }

		//"Question"
		public Keyword getQuestionKeyword_0() { return cQuestionKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"description" description=STRING
		public Group getGroup_3() { return cGroup_3; }

		//"description"
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_1_0() { return cDescriptionSTRINGTerminalRuleCall_3_1_0; }

		//"type" type=AnswerType
		public Group getGroup_4() { return cGroup_4; }

		//"type"
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }

		//type=AnswerType
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }

		//AnswerType
		public RuleCall getTypeAnswerTypeEnumRuleCall_4_1_0() { return cTypeAnswerTypeEnumRuleCall_4_1_0; }

		//"id" id=ID
		public Group getGroup_5() { return cGroup_5; }

		//"id"
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }

		//id=ID
		public Assignment getIdAssignment_5_1() { return cIdAssignment_5_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_5_1_0() { return cIdIDTerminalRuleCall_5_1_0; }

		//("required" req=INT)?
		public Group getGroup_6() { return cGroup_6; }

		//"required"
		public Keyword getRequiredKeyword_6_0() { return cRequiredKeyword_6_0; }

		//req=INT
		public Assignment getReqAssignment_6_1() { return cReqAssignment_6_1; }

		//INT
		public RuleCall getReqINTTerminalRuleCall_6_1_0() { return cReqINTTerminalRuleCall_6_1_0; }

		//alternatives+=Alternatives*
		public Assignment getAlternativesAssignment_7() { return cAlternativesAssignment_7; }

		//Alternatives
		public RuleCall getAlternativesAlternativesParserRuleCall_7_0() { return cAlternativesAlternativesParserRuleCall_7_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class AlternativesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Alternatives");
		private final Assignment cDescriptionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_0 = (RuleCall)cDescriptionAssignment.eContents().get(0);
		
		//Alternatives:
		//	description=STRING;
		public ParserRule getRule() { return rule; }

		//description=STRING
		public Assignment getDescriptionAssignment() { return cDescriptionAssignment; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_0() { return cDescriptionSTRINGTerminalRuleCall_0; }
	}
	
	
	public class DesignTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "DesignType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCDREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCDRCRDCompletelyRandomizedDesignKeyword_0_0 = (Keyword)cCDREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRCDBEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRCDBRCBDRandomizedCompleteBlockDesignKeyword_1_0 = (Keyword)cRCDBEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLSEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLSLSLatinSquareKeyword_2_0 = (Keyword)cLSEnumLiteralDeclaration_2.eContents().get(0);
		
		////Experimental Design
		//enum DesignType:
		//	CDR="CRD – Completely Randomized Design" | RCDB="RCBD – Randomized Complete Block Design" | LS="LS – Latin Square";
		public EnumRule getRule() { return rule; }

		//CDR="CRD – Completely Randomized Design" | RCDB="RCBD – Randomized Complete Block Design" | LS="LS – Latin Square"
		public Alternatives getAlternatives() { return cAlternatives; }

		//CDR="CRD – Completely Randomized Design"
		public EnumLiteralDeclaration getCDREnumLiteralDeclaration_0() { return cCDREnumLiteralDeclaration_0; }

		//"CRD – Completely Randomized Design"
		public Keyword getCDRCRDCompletelyRandomizedDesignKeyword_0_0() { return cCDRCRDCompletelyRandomizedDesignKeyword_0_0; }

		//RCDB="RCBD – Randomized Complete Block Design"
		public EnumLiteralDeclaration getRCDBEnumLiteralDeclaration_1() { return cRCDBEnumLiteralDeclaration_1; }

		//"RCBD – Randomized Complete Block Design"
		public Keyword getRCDBRCBDRandomizedCompleteBlockDesignKeyword_1_0() { return cRCDBRCBDRandomizedCompleteBlockDesignKeyword_1_0; }

		//LS="LS – Latin Square"
		public EnumLiteralDeclaration getLSEnumLiteralDeclaration_2() { return cLSEnumLiteralDeclaration_2; }

		//"LS – Latin Square"
		public Keyword getLSLSLatinSquareKeyword_2_0() { return cLSLSLatinSquareKeyword_2_0; }
	}

	public class AnswerTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "AnswerType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cComboBoxEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cComboBoxComboBoxKeyword_0_0 = (Keyword)cComboBoxEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCheckBoxesEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCheckBoxesCheckBoxesKeyword_1_0 = (Keyword)cCheckBoxesEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cOptionButtonsEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cOptionButtonsOptionButtonsKeyword_2_0 = (Keyword)cOptionButtonsEnumLiteralDeclaration_2.eContents().get(0);
		
		////Questions
		//enum AnswerType:
		//	ComboBox | CheckBoxes | OptionButtons;
		public EnumRule getRule() { return rule; }

		//ComboBox | CheckBoxes | OptionButtons
		public Alternatives getAlternatives() { return cAlternatives; }

		//ComboBox
		public EnumLiteralDeclaration getComboBoxEnumLiteralDeclaration_0() { return cComboBoxEnumLiteralDeclaration_0; }

		//"ComboBox"
		public Keyword getComboBoxComboBoxKeyword_0_0() { return cComboBoxComboBoxKeyword_0_0; }

		//CheckBoxes
		public EnumLiteralDeclaration getCheckBoxesEnumLiteralDeclaration_1() { return cCheckBoxesEnumLiteralDeclaration_1; }

		//"CheckBoxes"
		public Keyword getCheckBoxesCheckBoxesKeyword_1_0() { return cCheckBoxesCheckBoxesKeyword_1_0; }

		//OptionButtons
		public EnumLiteralDeclaration getOptionButtonsEnumLiteralDeclaration_2() { return cOptionButtonsEnumLiteralDeclaration_2; }

		//"OptionButtons"
		public Keyword getOptionButtonsOptionButtonsKeyword_2_0() { return cOptionButtonsOptionButtonsKeyword_2_0; }
	}

	public class MetricTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "MetricType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHardDataEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHardDataHardDataKeyword_0_0 = (Keyword)cHardDataEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSoftDataEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSoftDataSoftDataKeyword_1_0 = (Keyword)cSoftDataEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNormalizedDataEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNormalizedDataNormalizedDataKeyword_2_0 = (Keyword)cNormalizedDataEnumLiteralDeclaration_2.eContents().get(0);
		
		//// Metrica
		//enum MetricType:
		//	hardData | softData | normalizedData;
		public EnumRule getRule() { return rule; }

		//hardData | softData | normalizedData
		public Alternatives getAlternatives() { return cAlternatives; }

		//hardData
		public EnumLiteralDeclaration getHardDataEnumLiteralDeclaration_0() { return cHardDataEnumLiteralDeclaration_0; }

		//"hardData"
		public Keyword getHardDataHardDataKeyword_0_0() { return cHardDataHardDataKeyword_0_0; }

		//softData
		public EnumLiteralDeclaration getSoftDataEnumLiteralDeclaration_1() { return cSoftDataEnumLiteralDeclaration_1; }

		//"softData"
		public Keyword getSoftDataSoftDataKeyword_1_0() { return cSoftDataSoftDataKeyword_1_0; }

		//normalizedData
		public EnumLiteralDeclaration getNormalizedDataEnumLiteralDeclaration_2() { return cNormalizedDataEnumLiteralDeclaration_2; }

		//"normalizedData"
		public Keyword getNormalizedDataNormalizedDataKeyword_2_0() { return cNormalizedDataNormalizedDataKeyword_2_0; }
	}

	public class ColectTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ColectType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cContinuousEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cContinuousContinuousKeyword_0_0 = (Keyword)cContinuousEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIntercalatedEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIntercalatedIntercalatedKeyword_1_0 = (Keyword)cIntercalatedEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum ColectType:
		//	continuous | intercalated;
		public EnumRule getRule() { return rule; }

		//continuous | intercalated
		public Alternatives getAlternatives() { return cAlternatives; }

		//continuous
		public EnumLiteralDeclaration getContinuousEnumLiteralDeclaration_0() { return cContinuousEnumLiteralDeclaration_0; }

		//"continuous"
		public Keyword getContinuousContinuousKeyword_0_0() { return cContinuousContinuousKeyword_0_0; }

		//intercalated
		public EnumLiteralDeclaration getIntercalatedEnumLiteralDeclaration_1() { return cIntercalatedEnumLiteralDeclaration_1; }

		//"intercalated"
		public Keyword getIntercalatedIntercalatedKeyword_1_0() { return cIntercalatedIntercalatedKeyword_1_0; }
	}

	public class MetricUnitElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "MetricUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMinutesEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMinutesMinutesKeyword_0_0 = (Keyword)cMinutesEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cUcEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cUcUcKeyword_1_0 = (Keyword)cUcEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum MetricUnit:
		//	minutes | uc;
		public EnumRule getRule() { return rule; }

		//minutes | uc
		public Alternatives getAlternatives() { return cAlternatives; }

		//minutes
		public EnumLiteralDeclaration getMinutesEnumLiteralDeclaration_0() { return cMinutesEnumLiteralDeclaration_0; }

		//"minutes"
		public Keyword getMinutesMinutesKeyword_0_0() { return cMinutesMinutesKeyword_0_0; }

		//uc
		public EnumLiteralDeclaration getUcEnumLiteralDeclaration_1() { return cUcEnumLiteralDeclaration_1; }

		//"uc"
		public Keyword getUcUcKeyword_1_0() { return cUcUcKeyword_1_0; }
	}
	
	private ModelElements pModel;
	private ExperimentElementElements pExperimentElement;
	private ProcessElements pProcess;
	private ActivityElements pActivity;
	private TaskElements pTask;
	private RoleElements pRole;
	private ExperimentalPlanElements pExperimentalPlan;
	private FactorElements pFactor;
	private LevelsElements pLevels;
	private MetricsElements pMetrics;
	private ActivityMetricElements pActivityMetric;
	private TaskMetricElements pTaskMetric;
	private QuestionsElements pQuestions;
	private QuestionElements pQuestion;
	private AlternativesElements pAlternatives;
	private DesignTypeElements unknownRuleDesignType;
	private AnswerTypeElements unknownRuleAnswerType;
	private MetricTypeElements unknownRuleMetricType;
	private ColectTypeElements unknownRuleColectType;
	private MetricUnitElements unknownRuleMetricUnit;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ExpDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	elements+=ExperimentElement*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//ExperimentElement:
	//	("Process" process+=Process* "end") ("Experimental Plan" experiments+=ExperimentalPlan*)? ("General Questions"
	//	question+=Question*)?;
	public ExperimentElementElements getExperimentElementAccess() {
		return (pExperimentElement != null) ? pExperimentElement : (pExperimentElement = new ExperimentElementElements());
	}
	
	public ParserRule getExperimentElementRule() {
		return getExperimentElementAccess().getRule();
	}

	////WorkbreakdownStructure	
	//Process:
	//	(name=STRING "{" activities+=Activity* "}") ("metrics" metrics+=Metrics* "end")? ("Specific Questions"
	//	question+=Question* "end")?;
	public ProcessElements getProcessAccess() {
		return (pProcess != null) ? pProcess : (pProcess = new ProcessElements());
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}

	//Activity:
	//	"Activity" id=ID name=STRING next+=ID? role+=Role* ("{" tasks+=Task* "}")?;
	public ActivityElements getActivityAccess() {
		return (pActivity != null) ? pActivity : (pActivity = new ActivityElements());
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//Task:
	//	"Task" name=STRING;
	public TaskElements getTaskAccess() {
		return (pTask != null) ? pTask : (pTask = new TaskElements());
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}

	//Role:
	//	"Role" name=STRING;
	public RoleElements getRoleAccess() {
		return (pRole != null) ? pRole : (pRole = new RoleElements());
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}

	////CRD – Completely Randomized Design
	////RCBD – Randomized Complete Block Design
	////LS – Latin Square
	//ExperimentalPlan:
	//	"Design" name=STRING "type" type=DesignType "{" factor+=Factor* "}";
	public ExperimentalPlanElements getExperimentalPlanAccess() {
		return (pExperimentalPlan != null) ? pExperimentalPlan : (pExperimentalPlan = new ExperimentalPlanElements());
	}
	
	public ParserRule getExperimentalPlanRule() {
		return getExperimentalPlanAccess().getRule();
	}

	//Factor:
	//	"Factor" name=STRING "{" level+=Levels* "}";
	public FactorElements getFactorAccess() {
		return (pFactor != null) ? pFactor : (pFactor = new FactorElements());
	}
	
	public ParserRule getFactorRule() {
		return getFactorAccess().getRule();
	}

	//Levels:
	//	"Level" name=STRING;
	public LevelsElements getLevelsAccess() {
		return (pLevels != null) ? pLevels : (pLevels = new LevelsElements());
	}
	
	public ParserRule getLevelsRule() {
		return getLevelsAccess().getRule();
	}

	//Metrics:
	//	ActivityMetric | TaskMetric;
	public MetricsElements getMetricsAccess() {
		return (pMetrics != null) ? pMetrics : (pMetrics = new MetricsElements());
	}
	
	public ParserRule getMetricsRule() {
		return getMetricsAccess().getRule();
	}

	//ActivityMetric:
	//	"Metric" name=STRING "relates" processName+=STRING* "{" ("description" description=STRING) ("type" type=MetricType)
	//	("form" form=ColectType)? ("id" id=STRING) ("unit" unit=MetricUnit)? ("activityBegin" activityBegin=STRING)
	//	("activityEnd" activityEnd=STRING) "}";
	public ActivityMetricElements getActivityMetricAccess() {
		return (pActivityMetric != null) ? pActivityMetric : (pActivityMetric = new ActivityMetricElements());
	}
	
	public ParserRule getActivityMetricRule() {
		return getActivityMetricAccess().getRule();
	}

	//TaskMetric:
	//	"Metric" name=STRING "relates" processName+=STRING* "{" ("description" description=STRING) ("type" type=MetricType)
	//	("form" form=ColectType)? ("id" id=STRING) ("unit" unit=MetricUnit)? ("activities" activities=STRING) "}";
	public TaskMetricElements getTaskMetricAccess() {
		return (pTaskMetric != null) ? pTaskMetric : (pTaskMetric = new TaskMetricElements());
	}
	
	public ParserRule getTaskMetricRule() {
		return getTaskMetricAccess().getRule();
	}

	//Questions:
	//	question+=Question*;
	public QuestionsElements getQuestionsAccess() {
		return (pQuestions != null) ? pQuestions : (pQuestions = new QuestionsElements());
	}
	
	public ParserRule getQuestionsRule() {
		return getQuestionsAccess().getRule();
	}

	//Question:
	//	"Question" name=STRING "{" ("description" description=STRING) ("type" type=AnswerType) ("id" id=ID) ("required"
	//	req=INT)? alternatives+=Alternatives* "}";
	public QuestionElements getQuestionAccess() {
		return (pQuestion != null) ? pQuestion : (pQuestion = new QuestionElements());
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}

	//Alternatives:
	//	description=STRING;
	public AlternativesElements getAlternativesAccess() {
		return (pAlternatives != null) ? pAlternatives : (pAlternatives = new AlternativesElements());
	}
	
	public ParserRule getAlternativesRule() {
		return getAlternativesAccess().getRule();
	}

	////Experimental Design
	//enum DesignType:
	//	CDR="CRD – Completely Randomized Design" | RCDB="RCBD – Randomized Complete Block Design" | LS="LS – Latin Square";
	public DesignTypeElements getDesignTypeAccess() {
		return (unknownRuleDesignType != null) ? unknownRuleDesignType : (unknownRuleDesignType = new DesignTypeElements());
	}
	
	public EnumRule getDesignTypeRule() {
		return getDesignTypeAccess().getRule();
	}

	////Questions
	//enum AnswerType:
	//	ComboBox | CheckBoxes | OptionButtons;
	public AnswerTypeElements getAnswerTypeAccess() {
		return (unknownRuleAnswerType != null) ? unknownRuleAnswerType : (unknownRuleAnswerType = new AnswerTypeElements());
	}
	
	public EnumRule getAnswerTypeRule() {
		return getAnswerTypeAccess().getRule();
	}

	//// Metrica
	//enum MetricType:
	//	hardData | softData | normalizedData;
	public MetricTypeElements getMetricTypeAccess() {
		return (unknownRuleMetricType != null) ? unknownRuleMetricType : (unknownRuleMetricType = new MetricTypeElements());
	}
	
	public EnumRule getMetricTypeRule() {
		return getMetricTypeAccess().getRule();
	}

	//enum ColectType:
	//	continuous | intercalated;
	public ColectTypeElements getColectTypeAccess() {
		return (unknownRuleColectType != null) ? unknownRuleColectType : (unknownRuleColectType = new ColectTypeElements());
	}
	
	public EnumRule getColectTypeRule() {
		return getColectTypeAccess().getRule();
	}

	//enum MetricUnit:
	//	minutes | uc;
	public MetricUnitElements getMetricUnitAccess() {
		return (unknownRuleMetricUnit != null) ? unknownRuleMetricUnit : (unknownRuleMetricUnit = new MetricUnitElements());
	}
	
	public EnumRule getMetricUnitRule() {
		return getMetricUnitAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
